$(document).ready(function){
//anonymous function
$("h1,h2").click(function){
	$(this).css(backround-color","purple");
)};
$("h1,h2").mouseover(function){
	$(this).css(backround-color","black");
)};
$("h1").mousedown(function){
	$(this).css(backround-color","blue");
)};
$("h1").mousedown(function){
	$(this).css(backround-color","red");
)};
$("h1").mouseup(function){
	$(this).css(backround-color","orange");
)};
$("h1").mouseup(function){
	$(this).css(backround-color","yellow");
)};
$("h1").mouseleave(function){
	$(this).css(backround-color","purple");
)};
$("h3")click(function){
	$(h2).unbind("mouseup");
	$(h2).unbind("mousedown");
	)};
)};
